        <nav>
            <ul id="Menu">
                <li><a href="../vuescontrolleurs/index.php" title="Accueil">Accueil </a></li>
                <li><a href="../vuescontrolleurs/Contact.php" title="Contact"> Contact </a></li>
                <li><a href="../vuescontrolleurs/voirLesBiens.php" title="voirLesBiens">Voir les biens</a></li>
                <li><a href="../vuescontrolleurs/recherche.php" title="recherche">Recherche</a></li>
                <li><a href="../vuescontrolleurs/pageConnexion.php" title="pageConnexion">Connexion</a></li>
            </ul>
        </nav>
